name: invidious
description: Invidious API client for Dart and Flutter.
version: 0.1.1
repository: https://github.com/KRTirtho/invidious_dart

environment:
  sdk: ^3.5.3

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  dio: ^5.7.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
