part of '../model.dart';

@freezed
class InvidiousChannelObject with _$InvidiousChannelObject {
  factory InvidiousChannelObject({
    required String type,
    required String author,
    required String authorId,
    required String authorUrl,
    required bool authorVerified,
    required List<InvidiousThumbnailObject> authorThumbnails,
    required bool autoGenerated,
    required int subCount,
    required int videoCount,
    required String description,
    required String descriptionHtml,
  }) = _InvidiousChannelObject;

  factory InvidiousChannelObject.fromJson(Map<String, dynamic> json) =>
      _$InvidiousChannelObjectFromJson(json);
}
